#!/bin/bash

# Xro Agent Backend - Quick Start Guide

echo "🚀 Xro Agent Backend - System Ready!"
echo ""
echo "✅ All Systems Operational:"
echo "   ✓ PostgreSQL Database (Aiven)"
echo "   ✓ NVIDIA NIM LLM + Fallback"
echo "   ✓ 5 Agents (Main + 4 Specialized)"
echo "   ✓ 4 Shared Tools"
echo "   ✓ Bull Queue System"
echo "   ✓ Express API Server (28 routes)"
echo "   ✓ WebSocket Support"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 QUICK START COMMANDS:"
echo ""
echo "1. Development Mode (Both Server + Worker):"
echo "   npm run dev:all"
echo ""
echo "2. Server Only:"
echo "   npm start"
echo ""
echo "3. Worker Only (separate terminal):"
echo "   npm run worker"
echo ""
echo "4. Development with Auto-Reload:"
echo "   npm run dev"
echo ""
echo "5. Run Diagnostics:"
echo "   node test-connections.js"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🧪 TEST THE API:"
echo ""
echo "# Get Health Check:"
echo "curl http://localhost:3000/health"
echo ""
echo "# List Agents:"
echo "curl http://localhost:3000/api/agents"
echo ""
echo "# List Tools:"
echo "curl http://localhost:3000/api/tools"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🐳 DOCKER DEPLOYMENT:"
echo ""
echo "# Start all services with Docker:"
echo "docker-compose up -d"
echo ""
echo "# View logs:"
echo "docker-compose logs -f app"
echo ""
echo "# Stop services:"
echo "docker-compose down"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 SYSTEM INFO:"
echo ""
echo "Server Port:     3000"
echo "Database:        PostgreSQL (Aiven)"
echo "Cache:           Redis"
echo "Queue:           Bull"
echo "LLM Provider:    NVIDIA NIM (+ Fallback)"
echo "API Routes:      28 endpoints"
echo "Agents:          5 total (1 main + 4 sub)"
echo "Tools:           4 shared tools"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 DOCUMENTATION:"
echo "   • README.md - Full project documentation"
echo "   • SYSTEM_TEST_RESULTS.md - Test results"
echo "   • test-connections.js - Run diagnostics"
echo ""
echo "✨ System is ready for use!"
echo ""
