const logger = require("./logger");
const toolRegistry = require("../tools/ToolRegistry");

const EmbeddingTool = require("../tools/ai/EmbeddingTool.js");
const EntityExtractTool = require("../tools/ai/EntityExtractTool.js");
const KeywordExtractTool = require("../tools/ai/KeywordExtractTool.js");
const LanguageDetectTool = require("../tools/ai/LanguageDetectTool.js");
const SentimentTool = require("../tools/ai/SentimentTool.js");
const SpellCheckTool = require("../tools/ai/SpellCheckTool.js");
const SummarizeTool = require("../tools/ai/SummarizeTool.js");
const TextClassifyTool = require("../tools/ai/TextClassifyTool.js");
const DictionaryTool = require("../tools/api/DictionaryTool.js");
const DiscordWebhookTool = require("../tools/api/DiscordWebhookTool.js");
const EmailSendTool = require("../tools/api/EmailSendTool.js");
const ExchangeRateTool = require("../tools/api/ExchangeRateTool.js");
const GitHubApiTool = require("../tools/api/GitHubApiTool.js");
const IpGeolocationTool = require("../tools/api/IpGeolocationTool.js");
const NewsApiTool = require("../tools/api/NewsApiTool.js");
const OpenWeatherTool = require("../tools/api/OpenWeatherTool.js");
const SlackSendTool = require("../tools/api/SlackSendTool.js");
const TelegramSendTool = require("../tools/api/TelegramSendTool.js");
const DiffTool = require("../tools/code/DiffTool.js");
const JsEvalTool = require("../tools/code/JsEvalTool.js");
const JsonToSchemaTool = require("../tools/code/JsonToSchemaTool.js");
const JwtDecodeTool = require("../tools/code/JwtDecodeTool.js");
const JwtEncodeTool = require("../tools/code/JwtEncodeTool.js");
const MinifyTool = require("../tools/code/MinifyTool.js");
const RegexReplaceTool = require("../tools/code/RegexReplaceTool.js");
const RegexTestTool = require("../tools/code/RegexTestTool.js");
const SqlFormatterTool = require("../tools/code/SqlFormatterTool.js");
const SyntaxHighlightTool = require("../tools/code/SyntaxHighlightTool.js");
const CertificateTool = require("../tools/crypto/CertificateTool.js");
const ChecksumTool = require("../tools/crypto/ChecksumTool.js");
const DecryptTool = require("../tools/crypto/DecryptTool.js");
const EncryptTool = require("../tools/crypto/EncryptTool.js");
const HashTool = require("../tools/crypto/HashTool.js");
const HmacTool = require("../tools/crypto/HmacTool.js");
const KeyPairTool = require("../tools/crypto/KeyPairTool.js");
const PasswordGenTool = require("../tools/crypto/PasswordGenTool.js");
const RandomStringTool = require("../tools/crypto/RandomStringTool.js");
const UuidTool = require("../tools/crypto/UuidTool.js");
const Base64Tool = require("../tools/data/Base64Tool.js");
const CsvParseTool = require("../tools/data/CsvParseTool.js");
const CsvStringifyTool = require("../tools/data/CsvStringifyTool.js");
const DataFilterTool = require("../tools/data/DataFilterTool.js");
const DataGroupTool = require("../tools/data/DataGroupTool.js");
const DataMergeTool = require("../tools/data/DataMergeTool.js");
const DataSortTool = require("../tools/data/DataSortTool.js");
const DataValidationTool = require("../tools/data/DataValidationTool.js");
const JsonParseTool = require("../tools/data/JsonParseTool.js");
const JsonQueryTool = require("../tools/data/JsonQueryTool.js");
const JsonTransformTool = require("../tools/data/JsonTransformTool.js");
const XmlParseTool = require("../tools/data/XmlParseTool.js");
const XmlStringifyTool = require("../tools/data/XmlStringifyTool.js");
const YamlParseTool = require("../tools/data/YamlParseTool.js");
const YamlStringifyTool = require("../tools/data/YamlStringifyTool.js");
const CronParseTool = require("../tools/datetime/CronParseTool.js");
const CurrentTimeTool = require("../tools/datetime/CurrentTimeTool.js");
const DateAddTool = require("../tools/datetime/DateAddTool.js");
const DateDiffTool = require("../tools/datetime/DateDiffTool.js");
const DateFormatTool = require("../tools/datetime/DateFormatTool.js");
const DateParseTool = require("../tools/datetime/DateParseTool.js");
const DateSubtractTool = require("../tools/datetime/DateSubtractTool.js");
const StopwatchTool = require("../tools/datetime/StopwatchTool.js");
const TimestampTool = require("../tools/datetime/TimestampTool.js");
const TimezoneConvertTool = require("../tools/datetime/TimezoneConvertTool.js");
const CopyFileTool = require("../tools/file/CopyFileTool.js");
const DeleteFileTool = require("../tools/file/DeleteFileTool.js");
const FileHashTool = require("../tools/file/FileHashTool.js");
const FileInfoTool = require("../tools/file/FileInfoTool.js");
const FileSaveTool = require("../tools/file/FileSaveTool.js");
const FileListTool = require("../tools/file/FileListTool.js");
const FileReadContentTool = require("../tools/file/FileReadContentTool.js");
const FileDeleteTool = require("../tools/file/FileDeleteTool.js");
const ListDirTool = require("../tools/file/ListDirTool.js");
const MoveFileTool = require("../tools/file/MoveFileTool.js");
const ReadFileTool = require("../tools/file/ReadFileTool.js");
const SearchFilesTool = require("../tools/file/SearchFilesTool.js");
const TempFileTool = require("../tools/file/TempFileTool.js");
const WriteFileTool = require("../tools/file/WriteFileTool.js");
const CompoundInterestTool = require("../tools/finance/CompoundInterestTool.js");
const CurrencyFormatTool = require("../tools/finance/CurrencyFormatTool.js");
const DiscountCalcTool = require("../tools/finance/DiscountCalcTool.js");
const InvestmentCalcTool = require("../tools/finance/InvestmentCalcTool.js");
const LoanCalcTool = require("../tools/finance/LoanCalcTool.js");
const MortgageCalcTool = require("../tools/finance/MortgageCalcTool.js");
const TaxCalcTool = require("../tools/finance/TaxCalcTool.js");
const TipCalcTool = require("../tools/finance/TipCalcTool.js");
const AsciiArtTool = require("../tools/image/AsciiArtTool.js");
const ColorConvertTool = require("../tools/image/ColorConvertTool.js");
const ColorInfoTool = require("../tools/image/ColorInfoTool.js");
const ColorPaletteTool = require("../tools/image/ColorPaletteTool.js");
const ImageInfoTool = require("../tools/image/ImageInfoTool.js");
const PixelateTool = require("../tools/image/PixelateTool.js");
const QrDecodeTool = require("../tools/image/QrDecodeTool.js");
const QrEncodeTool = require("../tools/image/QrEncodeTool.js");
const AngleTool = require("../tools/math/AngleTool.js");
const BasicStatsTool = require("../tools/math/BasicStatsTool.js");
const CalculatorTool = require("../tools/math/CalculatorTool.js");
const CombinatoricsTool = require("../tools/math/CombinatoricsTool.js");
const ComplexTool = require("../tools/math/ComplexTool.js");
const CorrelationTool = require("../tools/math/CorrelationTool.js");
const LinearRegressionTool = require("../tools/math/LinearRegressionTool.js");
const MatrixTool = require("../tools/math/MatrixTool.js");
const NumberTheoryTool = require("../tools/math/NumberTheoryTool.js");
const PercentageTool = require("../tools/math/PercentageTool.js");
const PolynomialTool = require("../tools/math/PolynomialTool.js");
const ProbabilityTool = require("../tools/math/ProbabilityTool.js");
const RandomTool = require("../tools/math/RandomTool.js");
const RoundingTool = require("../tools/math/RoundingTool.js");
const SequenceTool = require("../tools/math/SequenceTool.js");
const SetTheoryTool = require("../tools/math/SetTheoryTool.js");
const StatisticsTool = require("../tools/math/StatisticsTool.js");
const TrigTool = require("../tools/math/TrigTool.js");
const UnitConverterTool = require("../tools/math/UnitConverterTool.js");
const VectorTool = require("../tools/math/VectorTool.js");
const DnsLookupTool = require("../tools/network/DnsLookupTool.js");
const HttpStatusTool = require("../tools/network/HttpStatusTool.js");
const IpInfoTool = require("../tools/network/IpInfoTool.js");
const MacLookupTool = require("../tools/network/MacLookupTool.js");
const MxLookupTool = require("../tools/network/MxLookupTool.js");
const PingTool = require("../tools/network/PingTool.js");
const PortScanTool = require("../tools/network/PortScanTool.js");
const SslCheckTool = require("../tools/network/SslCheckTool.js");
const TracerouteTool = require("../tools/network/TracerouteTool.js");
const WhoisTool = require("../tools/network/WhoisTool.js");
const ChemicalFormulaTool = require("../tools/science/ChemicalFormulaTool.js");
const DistanceConvertTool = require("../tools/science/DistanceConvertTool.js");
const PeriodicTableTool = require("../tools/science/PeriodicTableTool.js");
const PressureConvertTool = require("../tools/science/PressureConvertTool.js");
const ScientificNotationTool = require("../tools/science/ScientificNotationTool.js");
const SiPrefixTool = require("../tools/science/SiPrefixTool.js");
const TemperatureConvertTool = require("../tools/science/TemperatureConvertTool.js");
const WeightConvertTool = require("../tools/science/WeightConvertTool.js");
const CpuInfoTool = require("../tools/system/CpuInfoTool.js");
const DiskInfoTool = require("../tools/system/DiskInfoTool.js");
const EnvGetTool = require("../tools/system/EnvGetTool.js");
const MemoryInfoTool = require("../tools/system/MemoryInfoTool.js");
const OsInfoTool = require("../tools/system/OsInfoTool.js");
const PlatformTool = require("../tools/system/PlatformTool.js");
const ProcessInfoTool = require("../tools/system/ProcessInfoTool.js");
const SleepTool = require("../tools/system/SleepTool.js");
const UptimeTool = require("../tools/system/UptimeTool.js");
const WhichTool = require("../tools/system/WhichTool.js");
const EscapeTool = require("../tools/text/EscapeTool.js");
const GlobMatchTool = require("../tools/text/GlobMatchTool.js");
const IndentTool = require("../tools/text/IndentTool.js");
const LineSortTool = require("../tools/text/LineSortTool.js");
const SlugifyTool = require("../tools/text/SlugifyTool.js");
const StringCaseTool = require("../tools/text/StringCaseTool.js");
const StringJoinTool = require("../tools/text/StringJoinTool.js");
const StringLengthTool = require("../tools/text/StringLengthTool.js");
const StringPadTool = require("../tools/text/StringPadTool.js");
const StringReplaceTool = require("../tools/text/StringReplaceTool.js");
const StringReverseTool = require("../tools/text/StringReverseTool.js");
const StringSimilarityTool = require("../tools/text/StringSimilarityTool.js");
const StringSliceTool = require("../tools/text/StringSliceTool.js");
const StringSplitTool = require("../tools/text/StringSplitTool.js");
const StringTrimTool = require("../tools/text/StringTrimTool.js");
const SubstringTool = require("../tools/text/SubstringTool.js");
const TemplateTool = require("../tools/text/TemplateTool.js");
const TextDiffTool = require("../tools/text/TextDiffTool.js");
const TextWrapTool = require("../tools/text/TextWrapTool.js");
const TruncateTool = require("../tools/text/TruncateTool.js");
const CacheTool = require("../tools/utility/CacheTool.js");
const CompareTool = require("../tools/utility/CompareTool.js");
const CounterTool = require("../tools/utility/CounterTool.js");
const DebounceTool = require("../tools/utility/DebounceTool.js");
const DeepCloneTool = require("../tools/utility/DeepCloneTool.js");
const EchoTool = require("../tools/utility/EchoTool.js");
const IdGeneratorTool = require("../tools/utility/IdGeneratorTool.js");
const JsonSchemaTool = require("../tools/utility/JsonSchemaTool.js");
const MorseCodeTool = require("../tools/utility/MorseCodeTool.js");
const ObjectPathTool = require("../tools/utility/ObjectPathTool.js");
const RomanNumeralTool = require("../tools/utility/RomanNumeralTool.js");
const SemverTool = require("../tools/utility/SemverTool.js");
const ThrottleTool = require("../tools/utility/ThrottleTool.js");
const TypeCheckTool = require("../tools/utility/TypeCheckTool.js");
const ValidatorTool = require("../tools/utility/ValidatorTool.js");
const CookieParseTool = require("../tools/web/CookieParseTool.js");
const HtmlToTextTool = require("../tools/web/HtmlToTextTool.js");
const HttpDeleteTool = require("../tools/web/HttpDeleteTool.js");
const HttpGetTool = require("../tools/web/HttpGetTool.js");
const HttpPostTool = require("../tools/web/HttpPostTool.js");
const HttpPutTool = require("../tools/web/HttpPutTool.js");
const MarkdownToHtmlTool = require("../tools/web/MarkdownToHtmlTool.js");
const MimeTypeTool = require("../tools/web/MimeTypeTool.js");
const RssFetchTool = require("../tools/web/RssFetchTool.js");
const ScreenshotTool = require("../tools/web/ScreenshotTool.js");
const UrlEncodeTool = require("../tools/web/UrlEncodeTool.js");
const UrlParseTool = require("../tools/web/UrlParseTool.js");
const UserAgentTool = require("../tools/web/UserAgentTool.js");
const WebSearchTool = require("../tools/web/WebSearchTool.js");
const WebhookTool = require("../tools/web/WebhookTool.js");

/**
 * Initialize all tools
 */
async function initializeTools() {
  try {
    logger.info("Initializing tools...");

    toolRegistry.register("embedding", new EmbeddingTool());
    toolRegistry.register("entity_extract", new EntityExtractTool());
    toolRegistry.register("keyword_extract", new KeywordExtractTool());
    toolRegistry.register("language_detect", new LanguageDetectTool());
    toolRegistry.register("sentiment", new SentimentTool());
    toolRegistry.register("spell_check", new SpellCheckTool());
    toolRegistry.register("summarize", new SummarizeTool());
    toolRegistry.register("text_classify", new TextClassifyTool());
    toolRegistry.register("dictionary", new DictionaryTool());
    toolRegistry.register("discord_webhook", new DiscordWebhookTool());
    toolRegistry.register("email_send", new EmailSendTool());
    toolRegistry.register("exchange_rate", new ExchangeRateTool());
    toolRegistry.register("git_hub_api", new GitHubApiTool());
    toolRegistry.register("ip_geolocation", new IpGeolocationTool());
    toolRegistry.register("news_api", new NewsApiTool());
    toolRegistry.register("open_weather", new OpenWeatherTool());
    toolRegistry.register("slack_send", new SlackSendTool());
    toolRegistry.register("telegram_send", new TelegramSendTool());
    toolRegistry.register("diff", new DiffTool());
    toolRegistry.register("js_eval", new JsEvalTool());
    toolRegistry.register("json_to_schema", new JsonToSchemaTool());
    toolRegistry.register("jwt_decode", new JwtDecodeTool());
    toolRegistry.register("jwt_encode", new JwtEncodeTool());
    toolRegistry.register("minify", new MinifyTool());
    toolRegistry.register("regex_replace", new RegexReplaceTool());
    toolRegistry.register("regex_test", new RegexTestTool());
    toolRegistry.register("sql_formatter", new SqlFormatterTool());
    toolRegistry.register("syntax_highlight", new SyntaxHighlightTool());
    toolRegistry.register("certificate", new CertificateTool());
    toolRegistry.register("checksum", new ChecksumTool());
    toolRegistry.register("decrypt", new DecryptTool());
    toolRegistry.register("encrypt", new EncryptTool());
    toolRegistry.register("hash", new HashTool());
    toolRegistry.register("hmac", new HmacTool());
    toolRegistry.register("key_pair", new KeyPairTool());
    toolRegistry.register("password_gen", new PasswordGenTool());
    toolRegistry.register("random_string", new RandomStringTool());
    toolRegistry.register("uuid", new UuidTool());
    toolRegistry.register("base64", new Base64Tool());
    toolRegistry.register("csv_parse", new CsvParseTool());
    toolRegistry.register("csv_stringify", new CsvStringifyTool());
    toolRegistry.register("data_filter", new DataFilterTool());
    toolRegistry.register("data_group", new DataGroupTool());
    toolRegistry.register("data_merge", new DataMergeTool());
    toolRegistry.register("data_sort", new DataSortTool());
    toolRegistry.register("data_validation", new DataValidationTool());
    toolRegistry.register("json_parse", new JsonParseTool());
    toolRegistry.register("json_query", new JsonQueryTool());
    toolRegistry.register("json_transform", new JsonTransformTool());
    toolRegistry.register("xml_parse", new XmlParseTool());
    toolRegistry.register("xml_stringify", new XmlStringifyTool());
    toolRegistry.register("yaml_parse", new YamlParseTool());
    toolRegistry.register("yaml_stringify", new YamlStringifyTool());
    toolRegistry.register("cron_parse", new CronParseTool());
    toolRegistry.register("current_time", new CurrentTimeTool());
    toolRegistry.register("date_add", new DateAddTool());
    toolRegistry.register("date_diff", new DateDiffTool());
    toolRegistry.register("date_format", new DateFormatTool());
    toolRegistry.register("date_parse", new DateParseTool());
    toolRegistry.register("date_subtract", new DateSubtractTool());
    toolRegistry.register("stopwatch", new StopwatchTool());
    toolRegistry.register("timestamp", new TimestampTool());
    toolRegistry.register("timezone_convert", new TimezoneConvertTool());
    toolRegistry.register("copy_file", new CopyFileTool());
    toolRegistry.register("delete_file", new DeleteFileTool());
    toolRegistry.register("file_hash", new FileHashTool());
    toolRegistry.register("file_info", new FileInfoTool());
    toolRegistry.register("file_save", new FileSaveTool());
    toolRegistry.register("file_list", new FileListTool());
    toolRegistry.register("file_read_content", new FileReadContentTool());
    toolRegistry.register("file_delete", new FileDeleteTool());
    toolRegistry.register("list_dir", new ListDirTool());
    toolRegistry.register("move_file", new MoveFileTool());
    toolRegistry.register("read_file", new ReadFileTool());
    toolRegistry.register("search_files", new SearchFilesTool());
    toolRegistry.register("temp_file", new TempFileTool());
    toolRegistry.register("write_file", new WriteFileTool());
    toolRegistry.register("compound_interest", new CompoundInterestTool());
    toolRegistry.register("currency_format", new CurrencyFormatTool());
    toolRegistry.register("discount_calc", new DiscountCalcTool());
    toolRegistry.register("investment_calc", new InvestmentCalcTool());
    toolRegistry.register("loan_calc", new LoanCalcTool());
    toolRegistry.register("mortgage_calc", new MortgageCalcTool());
    toolRegistry.register("tax_calc", new TaxCalcTool());
    toolRegistry.register("tip_calc", new TipCalcTool());
    toolRegistry.register("ascii_art", new AsciiArtTool());
    toolRegistry.register("color_convert", new ColorConvertTool());
    toolRegistry.register("color_info", new ColorInfoTool());
    toolRegistry.register("color_palette", new ColorPaletteTool());
    toolRegistry.register("image_info", new ImageInfoTool());
    toolRegistry.register("pixelate", new PixelateTool());
    toolRegistry.register("qr_decode", new QrDecodeTool());
    toolRegistry.register("qr_encode", new QrEncodeTool());
    toolRegistry.register("angle", new AngleTool());
    toolRegistry.register("basic_stats", new BasicStatsTool());
    toolRegistry.register("calculator", new CalculatorTool());
    toolRegistry.register("combinatorics", new CombinatoricsTool());
    toolRegistry.register("complex", new ComplexTool());
    toolRegistry.register("correlation", new CorrelationTool());
    toolRegistry.register("linear_regression", new LinearRegressionTool());
    toolRegistry.register("matrix", new MatrixTool());
    toolRegistry.register("number_theory", new NumberTheoryTool());
    toolRegistry.register("percentage", new PercentageTool());
    toolRegistry.register("polynomial", new PolynomialTool());
    toolRegistry.register("probability", new ProbabilityTool());
    toolRegistry.register("random", new RandomTool());
    toolRegistry.register("rounding", new RoundingTool());
    toolRegistry.register("sequence", new SequenceTool());
    toolRegistry.register("set_theory", new SetTheoryTool());
    toolRegistry.register("statistics", new StatisticsTool());
    toolRegistry.register("trig", new TrigTool());
    toolRegistry.register("unit_converter", new UnitConverterTool());
    toolRegistry.register("vector", new VectorTool());
    toolRegistry.register("dns_lookup", new DnsLookupTool());
    toolRegistry.register("http_status", new HttpStatusTool());
    toolRegistry.register("ip_info", new IpInfoTool());
    toolRegistry.register("mac_lookup", new MacLookupTool());
    toolRegistry.register("mx_lookup", new MxLookupTool());
    toolRegistry.register("ping", new PingTool());
    toolRegistry.register("port_scan", new PortScanTool());
    toolRegistry.register("ssl_check", new SslCheckTool());
    toolRegistry.register("traceroute", new TracerouteTool());
    toolRegistry.register("whois", new WhoisTool());
    toolRegistry.register("chemical_formula", new ChemicalFormulaTool());
    toolRegistry.register("distance_convert", new DistanceConvertTool());
    toolRegistry.register("periodic_table", new PeriodicTableTool());
    toolRegistry.register("pressure_convert", new PressureConvertTool());
    toolRegistry.register("scientific_notation", new ScientificNotationTool());
    toolRegistry.register("si_prefix", new SiPrefixTool());
    toolRegistry.register("temperature_convert", new TemperatureConvertTool());
    toolRegistry.register("weight_convert", new WeightConvertTool());
    toolRegistry.register("cpu_info", new CpuInfoTool());
    toolRegistry.register("disk_info", new DiskInfoTool());
    toolRegistry.register("env_get", new EnvGetTool());
    toolRegistry.register("memory_info", new MemoryInfoTool());
    toolRegistry.register("os_info", new OsInfoTool());
    toolRegistry.register("platform", new PlatformTool());
    toolRegistry.register("process_info", new ProcessInfoTool());
    toolRegistry.register("sleep", new SleepTool());
    toolRegistry.register("uptime", new UptimeTool());
    toolRegistry.register("which", new WhichTool());
    toolRegistry.register("escape", new EscapeTool());
    toolRegistry.register("glob_match", new GlobMatchTool());
    toolRegistry.register("indent", new IndentTool());
    toolRegistry.register("line_sort", new LineSortTool());
    toolRegistry.register("slugify", new SlugifyTool());
    toolRegistry.register("string_case", new StringCaseTool());
    toolRegistry.register("string_join", new StringJoinTool());
    toolRegistry.register("string_length", new StringLengthTool());
    toolRegistry.register("string_pad", new StringPadTool());
    toolRegistry.register("string_replace", new StringReplaceTool());
    toolRegistry.register("string_reverse", new StringReverseTool());
    toolRegistry.register("string_similarity", new StringSimilarityTool());
    toolRegistry.register("string_slice", new StringSliceTool());
    toolRegistry.register("string_split", new StringSplitTool());
    toolRegistry.register("string_trim", new StringTrimTool());
    toolRegistry.register("substring", new SubstringTool());
    toolRegistry.register("template", new TemplateTool());
    toolRegistry.register("text_diff", new TextDiffTool());
    toolRegistry.register("text_wrap", new TextWrapTool());
    toolRegistry.register("truncate", new TruncateTool());
    toolRegistry.register("cache", new CacheTool());
    toolRegistry.register("compare", new CompareTool());
    toolRegistry.register("counter", new CounterTool());
    toolRegistry.register("debounce", new DebounceTool());
    toolRegistry.register("deep_clone", new DeepCloneTool());
    toolRegistry.register("echo", new EchoTool());
    toolRegistry.register("id_generator", new IdGeneratorTool());
    toolRegistry.register("json_schema", new JsonSchemaTool());
    toolRegistry.register("morse_code", new MorseCodeTool());
    toolRegistry.register("object_path", new ObjectPathTool());
    toolRegistry.register("roman_numeral", new RomanNumeralTool());
    toolRegistry.register("semver", new SemverTool());
    toolRegistry.register("throttle", new ThrottleTool());
    toolRegistry.register("type_check", new TypeCheckTool());
    toolRegistry.register("validator", new ValidatorTool());
    toolRegistry.register("cookie_parse", new CookieParseTool());
    toolRegistry.register("html_to_text", new HtmlToTextTool());
    toolRegistry.register("http_delete", new HttpDeleteTool());
    toolRegistry.register("http_get", new HttpGetTool());
    toolRegistry.register("http_post", new HttpPostTool());
    toolRegistry.register("http_put", new HttpPutTool());
    toolRegistry.register("markdown_to_html", new MarkdownToHtmlTool());
    toolRegistry.register("mime_type", new MimeTypeTool());
    toolRegistry.register("rss_fetch", new RssFetchTool());
    toolRegistry.register("screenshot", new ScreenshotTool());
    toolRegistry.register("url_encode", new UrlEncodeTool());
    toolRegistry.register("url_parse", new UrlParseTool());
    toolRegistry.register("user_agent", new UserAgentTool());
    toolRegistry.register("web_search", new WebSearchTool());
    toolRegistry.register("webhook", new WebhookTool());

    logger.info("Tools initialized", { toolNames: toolRegistry.getNames() });
    return toolRegistry;
  } catch (error) {
    logger.error("Failed to initialize tools", { error: error.message });
    throw error;
  }
}

module.exports = { initializeTools };